Don't use external shell for LLVM lit tests
LLVM-bump deprecated lit.formats.ShTest(execute_external=True),
it now hard-errors at config-parse time, and the option is scheduled for removal in LLVM-24

```
[1/1] cd /__w/AdaptiveCpp/AdaptiveCpp/build/tests-sscp/compiler && lit /__w/AdaptiveCpp/AdaptiveCpp/build/tests-sscp/compiler/sscp -v
FAILED: compiler/CMakeFiles/check-sscp /__w/AdaptiveCpp/AdaptiveCpp/build/tests-sscp/compiler/CMakeFiles/check-sscp
cd /__w/AdaptiveCpp/AdaptiveCpp/build/tests-sscp/compiler && lit /__w/AdaptiveCpp/AdaptiveCpp/build/tests-sscp/compiler/sscp -v
lit: /usr/local/lib/python3.10/dist-packages/lit/TestingConfig.py:164: fatal: unable to parse config file '/__w/AdaptiveCpp/AdaptiveCpp/AdaptiveCpp/tests/compiler/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/lit/TestingConfig.py", line 153, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/__w/AdaptiveCpp/AdaptiveCpp/AdaptiveCpp/tests/compiler/lit.cfg.py", line 6, in <module>
    config.test_format = lit.formats.ShTest(True)
  File "/usr/local/lib/python3.10/dist-packages/lit/formats/shtest.py", line 27, in __init__
    raise ValueError(
ValueError: execute_external=True is deprected as of LLVM-23 and the option will be removed in LLVM-24. Please move to using the internal shell (execute_external=False). If you still need to force external execution to allow time for migration, set force_execute_external=True
```