[CI] Fix macos build
In a couple of Vulkan PRs I have observed that the MacOS job not
specific to Vulkan have failed to build compiler-rt.

```
2026-07-02T06:58:04.0308840Z FAILED: [code=1] compiler-rt/lib/xray/CMakeFiles/RTXrayFDR.osx.dir/xray_fdr_logging.cpp.o
2026-07-02T06:58:04.0415460Z /Users/runner/work/AdaptiveCpp/AdaptiveCpp/build/bin/clang++ --target=arm64-apple-darwin25.4.0 -DSANITIZER_COMMON_NO_REDEFINE_BUILTINS -DXRAY_HAS_EXCEPTIONS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Users/runner/work/AdaptiveCpp/AdaptiveCpp/llvm/compiler-rt/lib/xray/.. -I/Users/runner/work/AdaptiveCpp/AdaptiveCpp/llvm/compiler-rt/lib/xray/../../include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -Wall -Wno-unused-parameter -O3 -DNDEBUG -std=c++17 -arch arm64 -isysroot /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -stdlib=libc++ -mmacosx-version-min=10.10 -isysroot /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -fPIC -fno-builtin -fno-exceptions -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -g -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-format -fno-rtti -MD -MT compiler-rt/lib/xray/CMakeFiles/RTXrayFDR.osx.dir/xray_fdr_logging.cpp.o -MF compiler-rt/lib/xray/CMakeFiles/RTXrayFDR.osx.dir/xray_fdr_logging.cpp.o.d -o compiler-rt/lib/xray/CMakeFiles/RTXrayFDR.osx.dir/xray_fdr_logging.cpp.o -c /Users/runner/work/AdaptiveCpp/AdaptiveCpp/llvm/compiler-rt/lib/xray/xray_fdr_logging.cpp
2026-07-02T06:58:04.0509020Z In file included from /Users/runner/work/AdaptiveCpp/AdaptiveCpp/llvm/compiler-rt/lib/xray/xray_fdr_logging.cpp:21:
2026-07-02T06:58:04.0609610Z In file included from /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/memory:998:
2026-07-02T06:58:04.0711420Z In file included from /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/iterator:693:
2026-07-02T06:58:04.0813710Z In file included from /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/__iterator/istreambuf_iterator.h:19:
2026-07-02T06:58:04.0826800Z In file included from /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/__string/char_traits.h:13:
2026-07-02T06:58:04.0828210Z In file included from /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/__algorithm/find.h:16:
2026-07-02T06:58:04.0829410Z /Applications/Xcode_26.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/__bit/countr.h:28:10: error: use of undeclared identifier '__builtin_ctzg'
2026-07-02T06:58:04.0830510Z    28 |   return __builtin_ctzg(__t, numeric_limits<_Tp>::digits);
2026-07-02T06:58:04.0830960Z       |          ^
```

This patch tries to fix this by bumping the cmake version through
removing the workaround that keeps cmake at an older version.