[VK][CI] Skip all buffer tests for Linux Vulkan Job
PR https://github.com/AdaptiveCpp/AdaptiveCpp/pull/2168 disabled the
`buffer_tests/buffer_shared_ptr` sycl test that was sporadically failing
in CI. Since being disabled I've seen another buffer test sporadically
failing in CI. To help keep CI green this patch disables able the buffer
tests until this issue can be investigated further in https://github.com/AdaptiveCpp/AdaptiveCpp/issues/2163

> fatal error: in "buffer_tests/buffer_uninitialized": memory access violation at address: 0x5609d35faf5a: no mapping at fault address

* https://github.com/AdaptiveCpp/AdaptiveCpp/actions/runs/30882765254/job/91908025724
* https://github.com/AdaptiveCpp/AdaptiveCpp/actions/runs/30817833026/job/91705121338